In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import warnings

warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')
X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
gnb = GaussianNB()

gnb.fit(X,y)

y_pred = gnb.predict(X_test)

print('Accuaracy Score: ', accuracy_score(y_test, y_pred))
print('Confusion Matrix: \n ', confusion_matrix(y_test, y_pred))
print('Classification Report: ', classification_report(y_test, y_pred))



Accuaracy Score:  1.0
Confusion Matrix: 
  [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:                precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [5]:
gnb = MultinomialNB()

gnb.fit(X,y)

y_pred = gnb.predict(X_test)

print('Accuaracy Score: ', accuracy_score(y_test, y_pred))
print('Confusion Matrix: \n ', confusion_matrix(y_test, y_pred))
print('Classification Report: ', classification_report(y_test, y_pred))


Accuaracy Score:  0.9333333333333333
Confusion Matrix: 
  [[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]
Classification Report:                precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.89      0.89      0.89         9
   virginica       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [6]:
gnb = BernoulliNB()

gnb.fit(X,y)

y_pred = gnb.predict(X_test)

print('Accuaracy Score: ', accuracy_score(y_test, y_pred))
print('Confusion Matrix: \n ', confusion_matrix(y_test, y_pred))
print('Classification Report: ', classification_report(y_test, y_pred))


Accuaracy Score:  0.3333333333333333
Confusion Matrix: 
  [[10  0  0]
 [ 9  0  0]
 [11  0  0]]
Classification Report:                precision    recall  f1-score   support

      setosa       0.33      1.00      0.50        10
  versicolor       0.00      0.00      0.00         9
   virginica       0.00      0.00      0.00        11

    accuracy                           0.33        30
   macro avg       0.11      0.33      0.17        30
weighted avg       0.11      0.33      0.17        30

